### ISSUE TITLE
Comments inside `project.entry_points` crashes

### ISSUE THREAD

**Issue by tusharsadhwani** [tox-dev/pyproject-fmt#18]
Test code:

```toml
[project.entry-points]
# test
alpha = { B = "b", "A.A" = "a" }
beta = { C = "c", D = "d" }
```

output:

```console
$ pyproject-fmt test.toml
Traceback (most recent call last):
  File "/home/tushar/code/pyproject-fmt/venv/bin/pyproject-fmt", line 8, in <module>
    sys.exit(run())
  File "/home/tushar/code/pyproject-fmt/src/pyproject_fmt/__main__.py", line 29, in run
    formatted = format_pyproject(config)
  File "/home/tushar/code/pyproject-fmt/src/pyproject_fmt/formatter/__init__.py", line 24, in format_pyproject
    _perform(parsed, conf)
  File "/home/tushar/code/pyproject-fmt/src/pyproject_fmt/formatter/__init__.py", line 13, in _perform
    fmt_project(parsed, conf)
  File "/home/tushar/code/pyproject-fmt/src/pyproject_fmt/formatter/project.py", line 44, in fmt_project
    order_keys(entry_point, (), sort_key=lambda k: k[0])
  File "/home/tushar/code/pyproject-fmt/src/pyproject_fmt/formatter/util.py", line 40, in order_keys
    body = table.value.body
AttributeError: 'str' object has no attribute 'body'
```

**Comment by tusharsadhwani** [comment]
It's a type error, and it seems that mypy couldn't catch it because of a wrong `cast()` being done.

Instead of `cast(X, obj)`, doing `assert isinstance(obj, X)` will help find the exact source of bugs. Casts should almost always be avoided imo.

**Comment by tusharsadhwani** [comment]
I've also stumbled upon a potential tomlkit bug :'(

doing `table.value.body.append(...)` in the `order_keys` method seems to cause problems in rare cases. `table.value._map` is a dictionary containing a mapping from key name to the index where it exists in the body, and in one of my test cases it doesn't get updated.

**Comment by tusharsadhwani** [comment]
Test case that triggers this on main branch:

```python
def test_entry_points_with_comments(fmt: Fmt) -> None:
    start = """
    [project.entry-points]
    # test

    beta = { C = "c", D = "d" }
    alpha = { B = "b", "A.A" = "a" }
    """
    expected = """
    [project.entry-points]
    # test

    alpha = { B = "b", "A.A" = "a" }
    beta = { C = "c", D = "d" }
    """
    fmt(fmt_project, start, expected)
```

**Comment by tusharsadhwani** [comment]
Related: https://github.com/sdispater/tomlkit/issues/184
