### ISSUE TITLE
Suport inline tables

### ISSUE THREAD

**Issue by kianmeng** [tox-dev/pyproject-fmt#36]
I've tried with other Python projects and it worked, but not for `pyproject-fmt` itself.

Running on:

```sh
$ python --version
Python 3.7.13
```

Steps to reproduce the error:

```sh
pipx install pyproject-fmt
git clone https://github.com/tox-dev/pyproject-fmt.git
cd pyproject-fmt
pyproject-fmt pyproject.toml 
```

```sh
Traceback (most recent call last):
  File "/home/foobar/.local/bin/pyproject-fmt", line 8, in <module>
    sys.exit(run())
  File "/home/foobar/.local/pipx/venvs/pyproject-fmt/lib/python3.7/site-packages/pyproject_fmt/__main__.py", line 29, in run
    formatted = format_pyproject(config)
  File "/home/foobar/.local/pipx/venvs/pyproject-fmt/lib/python3.7/site-packages/pyproject_fmt/formatter/__init__.py", line 24, in format_pyproject
    _perform(parsed, conf)
  File "/home/foobar/.local/pipx/venvs/pyproject-fmt/lib/python3.7/site-packages/pyproject_fmt/formatter/__init__.py", line 13, in _perform
    fmt_project(parsed, conf)
  File "/home/foobar/.local/pipx/venvs/pyproject-fmt/lib/python3.7/site-packages/pyproject_fmt/formatter/project.py", line 33, in fmt_project
    order_keys(opt_deps, (), sort_key=lambda k: k[0])
  File "/home/foobar/.local/pipx/venvs/pyproject-fmt/lib/python3.7/site-packages/pyproject_fmt/formatter/util.py", line 41, in order_keys
    body = table.value.body
AttributeError: 'dict' object has no attribute 'body'
```

**Comment by gaborbernat** [comment]
What version are you using? We released a fix just last night, https://pypi.org/project/pyproject-fmt/

**Comment by gaborbernat** [comment]
Simple reproducible:

```toml
[project]
optional-dependencies.test = [
  "a",
]
optional-dependencies.doc = [
  "b",
]
```

**Comment by RonnyPfannschmidt** [comment]
nm, its actually #70

**Comment by kianmeng** [comment]
LGTM.

```
$ python -V
Python 3.7.17

$ pipx install pyproject-fmt
git clone https://github.com/tox-dev/pyproject-fmt.git
cd pyproject-fmt
pyproject-fmt pyproject.toml 
...
no change for pyproject.toml
```
