### ISSUE TITLE
Crash on python_requires upper bound

### ISSUE THREAD

**Issue by AntoineD** [tox-dev/pyproject-fmt#99]
Minimal reproducer:
```console
❯ cat pyproject.toml
[project]
requires-python = ">=3.8, <3.11"
❯ pyproject-fmt pyproject.toml
Traceback (most recent call last):
  File "/home/ad/.local/bin/pyproject-fmt", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/__main__.py", line 55, in run
    results = [_handle_one(config, opts) for config in opts.configs]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/__main__.py", line 55, in <listcomp>
    results = [_handle_one(config, opts) for config in opts.configs]
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/__main__.py", line 28, in _handle_one
    formatted = format_pyproject(config)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/formatter/__init__.py", line 26, in format_pyproject
    _perform(parsed, conf)
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/formatter/__init__.py", line 14, in _perform
    fmt_project(parsed, conf)
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/formatter/project.py", line 86, in fmt_project
    _add_py_classifiers(project)
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/formatter/project.py", line 42, in _add_py_classifiers
    versions = [int(i) for i in requires[2:].split(".")[:2]]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ad/.local/pipx/venvs/pyproject-fmt/lib64/python3.11/site-packages/pyproject_fmt/formatter/project.py", line 42, in <listcomp>
    versions = [int(i) for i in requires[2:].split(".")[:2]]
                ^^^^^^
ValueError: invalid literal for int() with base 10: '8, <3'
```

**Comment by gaborbernat** [comment]
PR welcome.
